---
version: "0.1"
globalTimeout: 90
testSuiteTimeout: 90
testSuiteStep: 90
matrix:
  os: [mac]
  files: ["test_app.py"]
runson: ${matrix.os}
pre:
  - npm install playwright --save-exact
  - pip3 install -r requirement.txt --cache-dir CacheDir
  - npx playwright install
  - pip3 install pytest==7.2.1
cacheKey: '{{ checksum "requirement.txt" }}'
cacheDirectories:
  - CacheDir
testSuites:
  - python3 -m pytest $files
post:
  - cat yaml/win/.hyperexecute_matrix.yaml
