---
version: "0.1"
globalTimeout: 90
testSuiteTimeout: 90
testSuiteStep: 90
runson: mac
autosplit: true
retryOnFailure: true
maxRetries: 1
concurrency: 1
env:
  TARGET_OS: "MacOS Catalina"
cacheKey: '{{ checksum "requirement.txt" }}'
cacheDirectories:
  - CacheDir
pre:
  - npm install playwright --save-exact
  - pip3 install -r requirement.txt --cache-dir CacheDir
  - npx playwright install
  - pip3 install pytest==7.2.1

testDiscovery:
  type: raw
  mode: dynamic
  command: grep -lr 'def' *.py
testRunnerCommand: python3 -m pytest $test

post:
  - cat yaml/win/.hyperexecute_autosplits.yaml

runtime:
  language: python
  version: "3.7"

jobLabel: [playwright-pytest, mac, autosplit]