---
version: "0.1"
globalTimeout: 90
testSuiteTimeout: 90
testSuiteStep: 90
matrix:
  os: [win]
  files: ["test_app.py"]
runson: ${matrix.os}
pre:
  - npm install playwright --save-exact
  - pip install -r requirement.txt --cache-dir CacheDir
  - playwright install
cacheKey: '{{ checksum "requirement.txt" }}'
cacheDirectories:
  - CacheDir
testSuites:
  - pytest $files
post:
  - cat yaml/win/.hyperexecute_matrix.yaml

jobLabel: [playwright-pytest, win, matrix]